#!/usr/bin/env python3

from pathlib import Path
import os
import sys
from pprint import pprint as pp
from plumbum import FG, BG
from plumbum import local
import time

#--------------
# HELPERS
#--------------

#--------------
# CONSTANTS
#--------------
ROOT_PATH = Path(os.path.abspath(os.path.dirname(sys.argv[0])))
GATHER_PATH = Path(ROOT_PATH / 'gather')
DEFAULT_CONFIG = 'configs/sosp23.yml'
DURATION = 300
maestro = local["./maestro"]
#--------------
COMBINATIONS = [
  # antipode, cli , threads
  # ------------------------
  # baseline
  (False ,   1  ,  1),
  (False ,   1  ,  2),
  (False ,   1  ,  3),
  (False ,   1  ,  8),
  (False ,   1  ,  10),
  (False ,   1  ,  14),
  # with antipode
  (True  ,   1  ,  1),
  (True  ,   1  ,  2),
  (True  ,   1  ,  3),
  (True  ,   1  ,  8),
  (True  ,   1  ,  10),
  (True  ,   1  ,  14),
]


#--------------
# RUN
#--------------
# strong clean at the begining
maestro['--gcp', 'clean', '-strong'] & FG

# build the deployment
maestro['--gcp', 'build'] & FG

gathered_dirs = []
for antipode, clients, threads in COMBINATIONS:
  print('[INFO] New deployment starting:')
  print(f"\t > antipode: {antipode} // clients: {clients} // threads: {threads}\n")

  # deploy configuration
  maestro['--gcp', 'deploy', '-config', DEFAULT_CONFIG, '-clients', clients] & FG

  # run configuration with the proper arguments
  run_args = ['--gcp', 'run']
  # run_args = ['--gcp', 'run', '-prometheus', '-portainer']
  if antipode:
    run_args.append('-antipode')
  maestro[run_args] & FG

  # run the workload
  maestro['--gcp', 'wkld', '-d', DURATION, '-t', threads] & FG
  # find out the gather dir
  gather_path = max(GATHER_PATH.glob('**'), key=os.path.getmtime)
  gathered_dirs.append(gather_path.stem)

  # Look at info
  # maestro['--gcp', 'info', '-links'] & FG
  # input("[WAIT] Observe output ....")

  # soft clean
  maestro['--gcp', 'clean'] & FG
  print('\n[INFO] Done!')

# strong clean at the end
maestro['--gcp', 'clean', '-strong'] & FG

print("[INFO] Gathered results:")
print('\n'.join(gathered_dirs))