version: "3"
services:
#----------------------------------------------------------
# Admin tasks
#----------------------------------------------------------
  agent:
    image: portainer/agent
    # container_name: tasks.agent
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.agent
      AGENT_PORT: 9001
      # LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce
    command: -H tcp://tasks.agent:9001 --tlsskipverify --admin-password=${PORTAINER_PASSWORD_HASH}
    environment:
      # To generate a new password hash:
      # docker run --rm httpd:2.4-alpine htpasswd -nbB admin "antipode"
      PORTAINER_PASSWORD_HASH: $$2y$$05$$L912su0SNkU458ME1MyZauD4UFwEli69pIEQU/bYkla6Xc.WT8u3e
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
      # - default
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  agent_network:
    driver: overlay
  # default:
  #   driver: bridge

volumes:
  portainer_data: