- hosts: swarm_manager
  any_errors_fatal: true
  become: no
  gather_facts: no

  tasks:
    - name: Check that prometheus docker-compose exists
      stat:
        path: "/code/prometheus/docker-compose.yml"
      register: stat_result

    - name: Tear down existing prometheus services
      shell: >
        docker-compose -f /code/prometheus/docker-compose.yml down --remove-orphans --rmi local;
      when: stat_result.stat.exists