- hosts: swarm_manager
  any_errors_fatal: true
  become: no
  gather_facts: no

  tasks:
    - name: Undeploy train-ticket service
      shell: >
        docker stack rm train-ticket
      ignore_errors: yes


- hosts:
    - cluster
    - clients
  any_errors_fatal: true
  become: no
  gather_facts: no

  tasks:
    - name: Make worker nodes leave the Swarm
      shell: docker swarm leave -f
      register: out
      retries: 10
      delay: 10
      failed_when: "not(out.rc == 0 or 'This node is not part of a swarm' in out.stderr)"
      until: "(out.rc == 0 or 'This node is not part of a swarm' in out.stderr)"

    - name: Prune docker system
      shell: docker system prune --volumes -f


- hosts: swarm_manager
  any_errors_fatal: true
  become: no
  gather_facts: no

  tasks:
    - name: Make manager nodes leave the Swarm
      shell: docker swarm leave -f
      register: out
      failed_when: "not(out.rc == 0 or 'This node is not part of a swarm' in out.stderr)"