---
- hosts: swarm_manager
  any_errors_fatal: true
  gather_facts: no
  become: no

  tasks:
    - name: Create deploy folder
      file:
        path: /code/deploy/
        state: directory

    - name: Upload deploy folder
      synchronize:
        src: "{{ deploy_path }}/"
        dest: /code/deploy
        use_ssh_args: yes
        mode: push

- hosts: all
  any_errors_fatal: true
  become: no
  gather_facts: no

  tasks:
    - name: Create 'train-ticket' folder
      file:
        path: /code/train-ticket
        state: directory