---
- hosts: swarm_manager
  gather_facts: no
  become: yes
  any_errors_fatal: true

  tasks:
    - name: Run train-ticket stack
      shell: >
        docker stack deploy --with-registry-auth --compose-file /code/deploy/docker-compose.yml train-ticket
      register: out
      failed_when: "not(out.rc == 0) or 'fail' in out.stderr"

    - name: Check number of services running
      shell: >
        docker stack services train-ticket --format {% raw %}'{{.Name}}|{{.Replicas}}'{%endraw%} | wc -l
      register: num_services

    - name: Ensure all stack is running
      shell: >
        docker stack services train-ticket --format {% raw %}'{{.Name}}|{{.Replicas}}'{%endraw%} | grep '1/1' | wc -l
      register: num_deployed_services
      retries: 10
      delay: 45
      # compare number of services spawned with
      until: (num_deployed_services.stdout | int) == (num_services.stdout | int)

    - name: Pause until dashboard is reachable
      uri:
        url: "{{ dashboard_url }}"
        follow_redirects: none
        method: GET
      register: _result
      until: _result.status == 200
      retries: 30
      delay: 10